from src.models.byol import BYOL
from src.models.cpc import CPC
from src.models.efficientnet_lstm_pl import EfficientNetLSTM
from src.models.efficientnet_lstm_multi import EfficientNetLSTMMulti
from src.models.efficientnet_pl import EfficientNetPL
from src.models.ensemble_linear_eval import EnsembleLinear
from src.models.ensemble_lstm_linear_eval import EnsembleLSTMLinear
from src.models.linear_eval import LinearEval
from src.models.lstm_linear_eval import LSTMLinearEval
from src.models.moco import MoCo
from src.models.tclr import TCLR